### ISSUE TITLE
Update info on RTP programming comp 

### ISSUE THREAD

**Issue by aywang71** [PCHS-Programming-Club/pchs-programming-club.github.io#11]

**Comment by Hyperwizard42** [comment]
@dittoisditto , can you just put some TBA stuff for the page? Keep the code in a different file not linked to the website though, the descriptions may be useful later. I'd like to get the construction banner off of the website soon

**Comment by dittoisditto** [comment]
I've done it, but I'll keep the issue open until we actually update the page

**Comment by aywang71** [comment]
@draw-n probably a good time to wrap this issue as information is good now - not urgent for probably 1-2 weeks though
