### ISSUE TITLE
Should we remove the back button on resrc.html?

### ISSUE THREAD

**Issue by Hyperwizard42** [PCHS-Programming-Club/pchs-programming-club.github.io#23]
I don't really think theres a point to having it there - but i'm open to hearing out why it should be there

**Comment by Hyperwizard42** [comment]
same with about and competitions pages

**Comment by dittoisditto** [comment]
Honestly, it did seem a little weird to have it on there - if there is really no reason to have a back button, I'll get rid of it

**Comment by Hyperwizard42** [comment]
ok @dittoisditto lets get rid of it then - i don't think it contributes a lot to overall functionality or aesthetic
