### ISSUE TITLE
link club registration form to membership blurb, and add remind

### ISSUE THREAD

**Issue by aywang71** [PCHS-Programming-Club/pchs-programming-club.github.io#35]
lmk if you can't find the membership form link

**Comment by draw-n** [comment]
@Hyperwizard42 Is this it? https://forms.gle/kSJrkBsMURyFMFSe8 

Also, do you want me to just add a banner to index.html that has this link and the remind? Or something else?

**Comment by aywang71** [comment]
ah jeez... forgot to reply. Don't add a banner we can just keep it in the membership blurb - its more lowkey. Yes, that is the right form
